### ISSUE TITLE
async/await for nvm users on node versions under 7.6

### ISSUE THREAD

**Issue by alechp** [servexyz/repo-genesis-cli#6]
error:
```
± |master ✓| → repogen .repogen.js
/Users/kws/.nvm/versions/node/v6.11.1/lib/node_modules/repo-genesis-cli/cli.js:19
async function parse(config) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9
```

this occurs because async/await wasn't intro'd until [node 7.6](https://www.infoq.com/news/2017/02/node-76-async-await)

**Comment by alechp** [comment]
instead of changing babel compile target or implementing webpack, try out: https://rollupjs.org/guide/en

heard a lot of good things but never implemented before

**Comment by alechp** [comment]
Takeaway: start using NSTAR and port code.
